function setupDatabase(){let ss=ss_();Object.keys(SCHEMA).forEach(n=>{let sh=ss.getSheetByName(n)||ss.insertSheet(n),h=SCHEMA[n];sh.getRange(1,1,1,h.length).setValues([h]).setBackground('#145c3a').setFontColor('#fff').setFontWeight('bold');sh.setFrozenRows(1);sh.autoResizeColumns(1,h.length)});getOrCreateReportFolder_();clearCache_();SpreadsheetApp.getUi().alert('Food Tracker database is ready')}
function ss_(){if(CONFIG.SPREADSHEET_ID)return SpreadsheetApp.openById(CONFIG.SPREADSHEET_ID);let s=SpreadsheetApp.getActiveSpreadsheet();if(!s)throw Error('Bind script to a Google Sheet or set SPREADSHEET_ID');return s}
function bootstrap_(){let c=CacheService.getScriptCache(),z=c.get('bootstrap');if(z)return JSON.parse(z);let d={users:read_('Users'),meals:read_('Meals'),savedFoods:read_('SavedFoods'),vitaminProfiles:read_('VitaminProfiles'),vitaminLogs:read_('VitaminLogs'),fridgeItems:read_('Fridge'),reports:read_('Reports'),activeUserId:'',system:{spreadsheetName:ss_().getName(),reportFolderName:CONFIG.REPORT_FOLDER_NAME}},t=JSON.stringify(d);if(t.length<95000)c.put('bootstrap',t,CONFIG.CACHE_SECONDS);return d}
function read_(n){let sh=ss_().getSheetByName(n),h=SCHEMA[n];if(!sh||sh.getLastRow()<2)return[];return sh.getRange(2,1,sh.getLastRow()-1,h.length).getValues().map((r,i)=>{let o={_sheetRow:i+2};h.forEach((k,j)=>o[k]=norm_(k,r[j]));return o}).filter(o=>!truth_(o.deleted))}
function norm_(k,v){let nums=['age','height','weight','activity','goal','calories','protein','carbs','fat','fiber','sugar','sodium','water','servingQuantity','defaultQuantity','quantity'];if(nums.indexOf(k)>=0)return Number(v)||0;if(v instanceof Date)return Utilities.formatDate(v,CONFIG.TIMEZONE,'yyyy-MM-dd');return v==null?'':v}
function upsert_(n,o){valid_(n);if(!o.id)throw Error('Record id required');let sh=ss_().getSheetByName(n),row=find_(sh,o.id),vals=SCHEMA[n].map(k=>o[k]===undefined?'':o[k]);if(row)sh.getRange(row,1,1,vals.length).setValues([vals]);else sh.appendRow(vals)}
function softDelete_(n,id){valid_(n);let sh=ss_().getSheetByName(n),row=find_(sh,id),h=SCHEMA[n],dc=h.indexOf('deleted')+1,uc=h.indexOf('updatedAt')+1;if(!row)throw Error('Record not found');if(!dc)throw Error('Deletion unsupported');sh.getRange(row,dc).setValue(true);if(uc)sh.getRange(row,uc).setValue(new Date().toISOString())}
function find_(sh,id){if(sh.getLastRow()<2)return 0;let f=sh.getRange(2,1,sh.getLastRow()-1,1).createTextFinder(String(id)).matchEntireCell(true).findNext();return f?f.getRow():0}
function valid_(n){if(!SCHEMA[n])throw Error('Invalid sheet')}
function truth_(v){return v===true||v===1||String(v).toLowerCase()==='true'}
function clearCache_(){CacheService.getScriptCache().remove('bootstrap')}
function getOrCreateReportFolder_(){let p=PropertiesService.getScriptProperties(),id=p.getProperty('REPORT_FOLDER_ID');if(id){try{return DriveApp.getFolderById(id)}catch(x){}}let it=DriveApp.getFoldersByName(CONFIG.REPORT_FOLDER_NAME),f=it.hasNext()?it.next():DriveApp.createFolder(CONFIG.REPORT_FOLDER_NAME);p.setProperty('REPORT_FOLDER_ID',f.getId());return f}
